apiVersion: v1
kind: Service
metadata:
  name: {{ include "hero-app.fullname" . }}
  namespace: "hero-namespace"
  labels:
    app: "hero-app"
    name: "hero-app-web"
    {{- include "hero-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: "hero-app"
